# Copilot setup — WhatsApp Chat Reader

Instruccions mínimes per preparar l'entorn amb GitHub Copilot.

## Prerequisits
- Tenir GitHub Copilot activat al teu compte GitHub.
- Disposar de Python 3.8+ instal·lat.

## Passos ràpids
1. Clonar el repositori
   ```bash
   git clone https://github.com/trevSmart/whatsapp-chat-reader.git
   cd whatsapp-chat-reader
   ```

2. Crear i activar entorn virtual
   ```bash
   python3 -m venv venv_new
   source venv_new/bin/activate
   ```

3. Instal·lar Flask
   ```bash
   pip install flask
   ```

4. Activar Copilot a l'IDE
- Inicia sessió amb GitHub i habilita Copilot a la configuració de l'IDE.

## Recursos
- Documentació de Copilot: https://docs.github.com/en/copilot
- README del projecte: https://github.com/trevSmart/whatsapp-chat-reader/blob/main/README.md