# Copilot Environment Setup Instructions for WhatsApp Chat Reader

This file contains the necessary instructions to set up the Copilot environment for the WhatsApp Chat Reader project.

## Prerequisites
- Ensure you have GitHub Copilot enabled in your GitHub account.
- Python 3.8 or higher installed on your system.
- pip (Python package installer) available.

## Setup Steps
1. **Clone the repository**:
   ```bash
   git clone https://github.com/trevSmart/whatsapp-chat-reader.git
   cd whatsapp-chat-reader
   ```

2. **Install Dependencies**:
   Install Flask and other required Python packages:
   ```bash
   pip install flask flask-cors
   ```
   
   Or install all dependencies from requirements.txt:
   ```bash
   pip install -r requirements.txt
   ```

3. **Install the package in development mode**:
   ```bash
   pip install -e .
   ```

4. **Configure Copilot**:
   - Open your IDE with GitHub Copilot support.
   - Sign in with your GitHub account.
   - Enable GitHub Copilot in your IDE settings.

5. **Start Coding**:
   Begin using GitHub Copilot to assist you in the development of the WhatsApp Chat Reader project.

## Additional Resources
- [GitHub Copilot Documentation](https://docs.github.com/en/copilot)
- [WhatsApp Chat Reader Documentation](https://github.com/trevSmart/whatsapp-chat-reader/blob/main/README.md)
- [Flask Documentation](https://flask.palletsprojects.com/)

Happy Coding!
